### ISSUE TITLE
系统发现您网络不正常，需要验证 请输入右边图形中的数字

### ISSUE THREAD

**Issue by bigsuperangel** [qkqpttgf/herokuOnedrive#3]
系统提示：系统发现您网络不正常，需要验证
请输入右边图形中的数字，这个是什么问题呢

**Comment by qkqpttgf** [comment]
呃，我没遇到过。
你是在做什么操作……谁提示你的？

**Comment by 0bo** [comment]
> 系统提示：系统发现您网络不正常，需要验证
> 请输入右边图形中的数字，这个是什么问题呢

应该是类似cf那种机器人检测，你的ip地址不像是正常人使用的地址，让你输入验证码证明你是人不是机器。。。

**Comment by bigsuperangel** [comment]
找到原因了，里面放了一个index.html文件，删除掉就没问题了,可以关闭这条了

**Comment by qkqpttgf** [comment]
没问题了请自行关闭
