### ISSUE TITLE
fork方式搭建提示“The caller does not have permission to perform the action.”

### ISSUE THREAD

**Issue by 0bo** [qkqpttgf/herokuOnedrive#4]
点说明文件里deploy可以顺利搭建。

fork后在heroku中手动搭建，选择MSC模式，获得ID 和 Secret后，程序自动填写了refresh_token，但返回时显示“The caller does not have permission to perform the action.”

测试app地址：https://testhkod.herokuapp.com/

**Comment by qkqpttgf** [comment]
呃，这边刚刚打开新的无痕窗口，操作了一遍。
我的操作过程中有出现：heroku程序出错，返回上一页再操作就好；创建secret时跳到live个人帐号，直接输入5T帐号就可以；获取token时出错，说ID不在XXX里面，返回上一页再进入就拿到token了。
然后正常使用。
你要不换个帐号试下？或直接用默认MC模式？

**Comment by 0bo** [comment]
> 呃，这边刚刚打开新的无痕窗口，操作了一遍。
> 我的操作过程中有出现：heroku程序出错，返回上一页再操作就好；创建secret时跳到live个人帐号，直接输入5T帐号就可以；获取token时出错，说ID不在XXX里面，返回上一页再进入就拿到token了。
> 然后正常使用。
> 你要不换个帐号试下？或直接用默认MC模式？

额，它神奇的。。。自己好了？？原因不明。。。难道微软服务器需要响应时间？或者是浏览器cache的问题？
