### ISSUE TITLE
可否考虑做一个不依赖heroku的版本？

### ISSUE THREAD

**Issue by 0bo** [qkqpttgf/herokuOnedrive#5]
大佬的这个版本配合heroku可谓神器，各种功能非常齐全。

可否考虑做一个不依赖heroku在自己服务器上可以部署的版本？虽然有oneindex，但使用上还是您这个更舒服一些。

望考虑！

**Comment by qkqpttgf** [comment]
https://github.com/qkqpttgf/OneManager-php
给。

**Comment by 0bo** [comment]
> https://github.com/qkqpttgf/OneManager-php
> 给。

大佬请收下膝盖 Orz，已战略mark&fork！
